#!/usr/bin/env bash
set -euo pipefail

DRAGON_DIR=$HOME/.config/itch/apps/dragonruby-gtk/dragonruby-linux-amd64/
CURRENT_DIR=`pwd`
PROJECT_DIR=$(basename $CURRENT_DIR)

pushd $DRAGON_DIR
rm -rf $PROJECT_DIR
popd

cp -r ../$PROJECT_DIR $DRAGON_DIR/

pushd $DRAGON_DIR
./dragonruby-publish $PROJECT_DIR